# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool: Default

trigger:
  batch: true
  branches:
    include: [ master ] # branch names which will trigger a build
  paths:
    include:  [ audio/src/*, audio/audio-app-pipeline.yml ] # file paths which must match to trigger a build

steps:
# PowerShell
# Run a PowerShell script on Windows, macOS, or Linux.
- task: PowerShell@2
  inputs:
    targetType: filePath # Optional. Options: filePath, inline
    filePath: ./audio/scripts/deploy-apps.ps1 # Required when targetType == FilePath
    arguments:  -namePrefix stewless4 -region westus2 -userName $(userName) -password $(password) -tenantId $(tenantId) -subscriptionId %(subscriptionId)
    errorActionPreference: stop # Optional. Options: stop, continue, silentlyContinue
    failOnStderr: false # Optional
    ignoreLASTEXITCODE: false # Optional
    pwsh: true # Optional
    workingDirectory: ./audio/scripts # Optional